version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
      - apt-get update
      - apt-get install zip -y
      - apt-get install python2.7 -y
      - pip install --upgrade pip
      - echo "Done Installing"
  pre_build:
    commands:
      - echo "Before running build"
      - virtualenv venv --python=python2.7
      - . venv/bin/activate
      - pip install pytest==2.8.0
      - pip install Appium-Python-Client==0.20
      - ./scripts/pre_build.sh
  build:
    commands:
      - echo "Running all unit tests"
      - . venv/bin/activate
      - ./scripts/package_tests.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'