AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AWSDeviceFarmGetRunWebApp:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: deviceFarmGetRun
      Description: ''
      MemorySize: 128
      Timeout: 600
      Role: 'arn:aws:iam::047474169661:role/AWSLambdaRoleForStepFunctionDeviceFarm'
